steps:
- name: ubuntu
  args: ['bash', '-c', "echo '$COMMIT_SHA' > REVISION.txt"]
- name: gcr.io/cloud-builders/gsutil
  args:
    - 'cp'
    - '-r'
    - 'src/function-source.zip'
    - 'gs://source-test-bjvc'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - main
  - --source=gs://source-test-bjvc/function-source.zip
  - --trigger-topic=projects/ancient-vortex-298120/topics/prueba
  - --runtime=python38
  - --allow-unauthenticated